config/routes.rb
Rails.application.routes.draw do
  resources :produtos do
    get :buscar_por_codigo, on: :collection
  end

  get 'dashboard/index'
  get 'relatorios', to: 'relatorios#index'
  get 'produtos/buscar_por_codigo', to: 'produtos#buscar_por_codigo'

  resources :encomendas do
    get 'novo_produto_campo', on: :collection
  end

  resources :compras
  resources :clientes
  resources :dividas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "dashboard#index"

end

app/models/produto.rb
class Produto < ApplicationRecord
  has_many :encomenda_produtos, dependent: :destroy
  has_many :encomendas, through: :encomenda_produtos

  validates :nome, presence: true
  validates :preco, presence: true, numericality: { greater_than: 0 }
  validates :codigo_barra, presence: true, uniqueness: true
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_path, status: :see_other, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buscar_por_codigo
    codigo = params[:codigo]
    produto = Produto.where("REPLACE(codigo_barra, '-', '') = ?", codigo).first

    if produto
      render json: produto
    else
      render json: { error: "Produto não encontrado" }, status: :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :preco, :codigo_barra)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true, class: "mt-4") do |form| %>
  <% if produto.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(produto.errors.count, "erro") %> impediram este produto de ser salvo:</h4>
      <ul>
        <% produto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :nome, "Nome do Produto", class: "form-label" %>
    <%= form.text_field :nome, class: "form-control", placeholder: "Ex: Panela Antiaderente" %>
  </div>

  <div class="mb-3">
    <%= form.label :preco, "Preço (R$)", class: "form-label" %>
    <%= form.number_field :preco, step: 0.01, class: "form-control", placeholder: "Ex: 120.50" %>
  </div>

  <div class="mb-3">
    <%= form.label :codigo_barra, "Código de Barras", class: "form-label" %>
    <%= form.text_field :codigo_barra, class: "form-control", placeholder: "Escaneie ou digite o código" %>
  </div>

  <div class="text-end">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">
  <p>
    <strong>Nome:</strong>
    <%= produto.nome %>
  </p>

  <p>
    <strong>Preco:</strong>
    <%= produto.preco %>
  </p>

  <p>
    <strong>Codigo barra:</strong>
    <%= produto.codigo_barra %>
  </p>

</div>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Show this produto", @produto %> |
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<div id="produtos">
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Show this produto", produto %>
    </p>
  <% end %>
</div>

<%= link_to "New produto", new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Edit this produto", edit_produto_path(@produto) %> |
  <%= link_to "Back to produtos", produtos_path %>

  <%= button_to "Destroy this produto", @produto, method: :delete %>
</div>